[glam]
name = "graveyard"
version = "0.1.0"
author = "Dan Donche"
description = "Goblin's no-DB flat-file web framework."
license = "MIT"
entry = "graveyard.gbln"

[provides]
actions = [
    "graveyard::create_shard",
    "graveyard::save_shard",
    "graveyard::read_shard",
    "graveyard::update_shard",
    "graveyard::delete_shard",
    "graveyard::shard_path_for",
    "graveyard::shard_bucket",
    "graveyard::shard_meta",
    "graveyard::shard_body",
    "graveyard::shard_id_dir_for",
    "graveyard::shard_version_files",
    "graveyard::latest_version_on_disk",

    "graveyard::model_registry_path",
    "graveyard::registry_id",
    "graveyard::load_models_registry",
    "graveyard::save_models_registry",
    "graveyard::load_model",
    "graveyard::save_model",
    "graveyard::model_id",
    "graveyard::model_name",
    "graveyard::register_model",
    "graveyard::field_id",
    "graveyard::register_field",
    "graveyard::register_model_with_fields",

    "graveyard::index_path_for",
    "graveyard::read_index",
    "graveyard::write_index",
    "graveyard::find_entry_pos",
    "graveyard::append_to_index!",
    "graveyard::set_current_version!",
    "graveyard::remove_from_index!",
    "graveyard::latest_version",

    "graveyard::write_generated_model_files"
]

values = [
    "#graveyard::storage",
    "#graveyard::shard_fence",
    "#graveyard::models_dir",
    "#graveyard::models_registry_path"
]